// images
export const GET_FILE_LIST = "GET FILE LIST";
export const UPLOAD_FILE = "UPLOAD FILE";

// authentication
export const PROFILE_PHOTO_UPLOADED = "PROFILE PHOTO UPLOADED";
export const RESET_PROFILE_PHOTO = "RESET PROFILE PHOTO";
export const USER_REGISTERED = "USER REGISTERED";
export const USER_LOGGED_IN = "USER LOGGED IN";
export const USER_LOGGED_OUT = "USER LOGGED OUT";
export const USER_INFO_UPDATED = "USER INFO UPDATED";
export const USER_INFO_FETCHED = "USER INFO FETCHED";

// product
export const PRODUCT_UPLOADED = "PRODUCT UPLOADED";
export const USER_PRODUCT_LIST_RETRIEVED = "USER PRODUCT LIST RETRIEVED";
export const GALLERY_ITEM_INFO_RETRIEVED = "GALLERY ITEM INFO RETRIEVED";
export const GALLERY_ITEM_INFO_UPDATED = "GALLERY ITEM INFO UPDATED";
export const GALLERY_ITEM_DELETED = "GALLERY_ITEM_DELETED";

// home 
export const ALL_PRODUCTS_RETRIEVED = "ALL PRODUCTS RETRIEVED";
export const HOME_DATA_RETRIEVED = "HOME DATA RETRIEVED";
export const EXPLORE_DATA_RETRIEVED = "EXPLORE DATA RETRIEVED";