//images
export const GET_FILE_LIST = "GET FILE LIST";
export const UPLOAD_FILE = "UPLOAD FILE";

//authentication
export const PROFILE_PHOTO_UPLOADED = "PROFILE PHOTO UPLOADED";
export const RESET_PROFILE_PHOTO = "RESET PROFILE PHOTO";
export const USER_REGISTERED = "USER REGISTERED";