//images
export const GET_FILE_LIST = "GET FILE LIST";
export const UPLOAD_FILE = "UPLOAD FILE";

//authentication
export const PROFILE_PHOTO_UPLOADED = "PROFILE PHOTO UPLOADED";
export const RESET_PROFILE_PHOTO = "RESET PROFILE PHOTO";
export const USER_REGISTERED = "USER REGISTERED";
export const USER_LOGGED_IN = "USER LOGGED IN";
export const USER_LOGGED_OUT = "USER LOGGED OUT";
export const USER_INFO_UPDATED = "USER INFO UPDATED";

//product
export const PRODUCT_UPLOADED = "PRODUCT UPLOADED";